CREATE TABLE IF NOT EXISTS solicitudes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombreCliente VARCHAR(100) NOT NULL,
  correo VARCHAR(100) NOT NULL,
  asunto VARCHAR(150) NOT NULL,
  descripcion TEXT,
  estado VARCHAR(30) NOT NULL DEFAULT 'pendiente',
  fechaCreacion DATETIME DEFAULT CURRENT_TIMESTAMP,
  fechaActualizacion DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);